/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    sessions: Session;
    'email-jobs': EmailJob;
    classes: Class;
    memberships: Membership;
    invites: Invite;
    questions: Question;
    assignments: Assignment;
    attempts: Attempt;
    attachments: Attachment;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    sessions: SessionsSelect<false> | SessionsSelect<true>;
    'email-jobs': EmailJobsSelect<false> | EmailJobsSelect<true>;
    classes: ClassesSelect<false> | ClassesSelect<true>;
    memberships: MembershipsSelect<false> | MembershipsSelect<true>;
    invites: InvitesSelect<false> | InvitesSelect<true>;
    questions: QuestionsSelect<false> | QuestionsSelect<true>;
    assignments: AssignmentsSelect<false> | AssignmentsSelect<true>;
    attempts: AttemptsSelect<false> | AttemptsSelect<true>;
    attachments: AttachmentsSelect<false> | AttachmentsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  role: 'teacher' | 'student' | 'admin';
  emailConfirmed?: boolean | null;
  emailConfirmationTokenHash?: string | null;
  emailConfirmationTokenExpiresAt?: number | null;
  passwordResetTokenHash?: string | null;
  passwordResetTokenExpiresAt?: number | null;
  blocked?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions".
 */
export interface Session {
  id: string;
  sessionId: string;
  userId: string;
  role: 'teacher' | 'student';
  expiresAt: number;
  revoked?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-jobs".
 */
export interface EmailJob {
  id: string;
  userId: string;
  to: string;
  subject: string;
  body: string;
  status: 'pending' | 'claimed' | 'sent' | 'failed';
  attempts?: number | null;
  nextAttemptAt?: number | null;
  claimedAt?: number | null;
  leaseExpiresAt?: number | null;
  lastError?: string | null;
  createdAt: number;
  sentAt?: number | null;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "classes".
 */
export interface Class {
  id: string;
  ownerId: string;
  subjectVersionId: string;
  name: string;
  archivedAt?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "memberships".
 */
export interface Membership {
  id: string;
  classId: string;
  studentId: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invites".
 */
export interface Invite {
  id: string;
  code: string;
  classId: string;
  ownerId: string;
  createdAt: number;
  expiresAt: number;
  usedBy?: string | null;
  usedAt?: number | null;
  revoked?: boolean | null;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "questions".
 */
export interface Question {
  id: string;
  subjectVersionId: string;
  code: string;
  revisionNumber: number;
  type: 'single-choice' | 'multiple-choice' | 'short-text' | 'extended-text';
  topic: string;
  stem: string;
  options?:
    | {
        id: string;
        text: string;
      }[]
    | null;
  answerKey?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  points: number;
  source: 'fipi' | 'authored';
  editorStatus: 'draft' | 'review' | 'published' | 'retired';
  publishedAt?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assignments".
 */
export interface Assignment {
  id: string;
  ownerId: string;
  classId: string;
  title: string;
  status: 'draft' | 'assigned';
  dueAt?: number | null;
  questionSnapshot: {
    code: string;
    type: string;
    topic: string;
    stem: string;
    options?:
      | {
          id: string;
          text: string;
        }[]
      | null;
    answerKey?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    points: number;
    id?: string | null;
  }[];
  recipientIds: {
    id?: string | null;
  }[];
  createdAt: number;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attempts".
 */
export interface Attempt {
  id: string;
  assignmentId: string;
  classId: string;
  ownerId: string;
  studentId: string;
  title: string;
  dueAt?: number | null;
  subjectVersionId: string;
  status: 'assigned' | 'in_progress' | 'submitted' | 'checked';
  answers?:
    | {
        code: string;
        value?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        attachmentIds?:
          | {
              id?: string | null;
            }[]
          | null;
        clientVersion?: number | null;
        savedAt?: number | null;
        id?: string | null;
      }[]
    | null;
  scores?:
    | {
        code: string;
        auto?: number | null;
        manual?: number | null;
        teacherComment?: string | null;
        flaggedForReview?: boolean | null;
        id?: string | null;
      }[]
    | null;
  totalScore?: number | null;
  maxScore?: number | null;
  submittedAt?: number | null;
  checkedAt?: number | null;
  idempotencyKey?: string | null;
  comments?:
    | {
        authorId: string;
        authorRole: 'teacher' | 'student';
        internal?: boolean | null;
        body: string;
        createdAt: number;
        id?: string | null;
      }[]
    | null;
  createdAt: number;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attachments".
 */
export interface Attachment {
  id: string;
  attemptId: string;
  questionCode: string;
  studentId: string;
  storedName: string;
  originalName: string;
  mimeType: string;
  size: number;
  createdAt: number;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'sessions';
        value: string | Session;
      } | null)
    | ({
        relationTo: 'email-jobs';
        value: string | EmailJob;
      } | null)
    | ({
        relationTo: 'classes';
        value: string | Class;
      } | null)
    | ({
        relationTo: 'memberships';
        value: string | Membership;
      } | null)
    | ({
        relationTo: 'invites';
        value: string | Invite;
      } | null)
    | ({
        relationTo: 'questions';
        value: string | Question;
      } | null)
    | ({
        relationTo: 'assignments';
        value: string | Assignment;
      } | null)
    | ({
        relationTo: 'attempts';
        value: string | Attempt;
      } | null)
    | ({
        relationTo: 'attachments';
        value: string | Attachment;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  emailConfirmed?: T;
  emailConfirmationTokenHash?: T;
  emailConfirmationTokenExpiresAt?: T;
  passwordResetTokenHash?: T;
  passwordResetTokenExpiresAt?: T;
  blocked?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions_select".
 */
export interface SessionsSelect<T extends boolean = true> {
  sessionId?: T;
  userId?: T;
  role?: T;
  expiresAt?: T;
  revoked?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-jobs_select".
 */
export interface EmailJobsSelect<T extends boolean = true> {
  userId?: T;
  to?: T;
  subject?: T;
  body?: T;
  status?: T;
  attempts?: T;
  nextAttemptAt?: T;
  claimedAt?: T;
  leaseExpiresAt?: T;
  lastError?: T;
  createdAt?: T;
  sentAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "classes_select".
 */
export interface ClassesSelect<T extends boolean = true> {
  ownerId?: T;
  subjectVersionId?: T;
  name?: T;
  archivedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "memberships_select".
 */
export interface MembershipsSelect<T extends boolean = true> {
  classId?: T;
  studentId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invites_select".
 */
export interface InvitesSelect<T extends boolean = true> {
  code?: T;
  classId?: T;
  ownerId?: T;
  createdAt?: T;
  expiresAt?: T;
  usedBy?: T;
  usedAt?: T;
  revoked?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "questions_select".
 */
export interface QuestionsSelect<T extends boolean = true> {
  subjectVersionId?: T;
  code?: T;
  revisionNumber?: T;
  type?: T;
  topic?: T;
  stem?: T;
  options?:
    | T
    | {
        id?: T;
        text?: T;
      };
  answerKey?: T;
  points?: T;
  source?: T;
  editorStatus?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assignments_select".
 */
export interface AssignmentsSelect<T extends boolean = true> {
  ownerId?: T;
  classId?: T;
  title?: T;
  status?: T;
  dueAt?: T;
  questionSnapshot?:
    | T
    | {
        code?: T;
        type?: T;
        topic?: T;
        stem?: T;
        options?:
          | T
          | {
              id?: T;
              text?: T;
            };
        answerKey?: T;
        points?: T;
        id?: T;
      };
  recipientIds?:
    | T
    | {
        id?: T;
      };
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attempts_select".
 */
export interface AttemptsSelect<T extends boolean = true> {
  assignmentId?: T;
  classId?: T;
  ownerId?: T;
  studentId?: T;
  title?: T;
  dueAt?: T;
  subjectVersionId?: T;
  status?: T;
  answers?:
    | T
    | {
        code?: T;
        value?: T;
        attachmentIds?:
          | T
          | {
              id?: T;
            };
        clientVersion?: T;
        savedAt?: T;
        id?: T;
      };
  scores?:
    | T
    | {
        code?: T;
        auto?: T;
        manual?: T;
        teacherComment?: T;
        flaggedForReview?: T;
        id?: T;
      };
  totalScore?: T;
  maxScore?: T;
  submittedAt?: T;
  checkedAt?: T;
  idempotencyKey?: T;
  comments?:
    | T
    | {
        authorId?: T;
        authorRole?: T;
        internal?: T;
        body?: T;
        createdAt?: T;
        id?: T;
      };
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attachments_select".
 */
export interface AttachmentsSelect<T extends boolean = true> {
  attemptId?: T;
  questionCode?: T;
  studentId?: T;
  storedName?: T;
  originalName?: T;
  mimeType?: T;
  size?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}